# Generated by Django 4.2.3 on 2023-07-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0002_quiz_alter_weuser_options_quizattempt_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welearn.weuser'),
        ),
    ]
