# Generated by Django 4.2.3 on 2023-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0003_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='date_attempted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
