# Generated by Django 4.2.3 on 2023-07-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0004_alter_quizattempt_date_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welearn.quiz'),
        ),
    ]
