# Generated by Django 4.2.3 on 2023-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0005_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='max_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
