# Generated by Django 4.2.3 on 2023-07-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0006_quizattempt_max_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='ordering',
        ),
    ]
