# Generated by Django 4.2.3 on 2023-07-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0007_userbillinginfo_delete_billinginfo_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbillinginfo',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='userbillinginfo',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
