# Generated by Django 4.2.3 on 2023-07-22 22:59

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0012_quizattempt_is_passed_alter_course_registered_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('billing_address1', models.CharField(max_length=200)),
                ('billing_address2', models.CharField(max_length=200)),
                ('payment_info', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_holder_name', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('cvv', models.CharField(blank=True, max_length=3)),
                ('expiry_date', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
