# Generated by Django 4.2.3 on 2023-07-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0015_tier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillinginfo',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welearn.tier'),
        ),
    ]
