# Generated by Django 4.2.3 on 2023-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0017_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillinginfo',
            name='paypal_pid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
